### PR TITLE
Updates to the fuzzer assignment, Fall 2019

### PR DESCRIPTION
**Pull request by andymeneely**
Here's a branch and PR for all of the edits we want to make for the fuzzer assignment.

Feel free to suggest things and comment!

### CODE REVIEW

**Comment by andymeneely** [comment]
Other things I've been meaning to do:

  - [ ] Get latest python on Dockerfile. There's some stuff that's different between 3.5 and 3.7.
  - [ ] Update instructions that students should NOT be using below Python 3.7.
  - [ ] Allow node.js. Change instructions and put it on the Dockerfile
  - [ ] Install mechanicalsoup on the image
  - [ ] Get fuzzer-tests on XAMPP 
  - [ ] Get Dockerfile and XAMPP onto the same DVWA version
  - [ ] Update example output to a good one from this semester
  - [ ] Move this repo to an organization?
  - [ ] Make CI requirements clearer (i.e. make them required unless you met with a TA or instructor and they couldn't solve it)
  - [ ] Install python's mechanize on the image
  - [ ] Add an actual example command for the fuzzer tests and put that into the CI yml and site

**Comment by CraftSpider** [comment]
`fuzz.rb` to `fuzz.py` for the python examples?

**Comment by vincent-li-dev** [comment]
fuzzer-tests links have `./` as the prefix. DVWA doesn't really test for this. I got my functions to work for DVWA and then when I run fuzzer-tests, everything just breaks. I thought both tests were used in grading, maybe mention that only running against DVWA is graded.

**Comment by andymeneely** [comment]
Merged the changes in to our repo.

**Pull request closed without merging**
